### ISSUE TITLE
Java 1.8 compilation runtime error

### ISSUE THREAD

**Issue by madhephaestus** [OmniscientDebugger/LewisOmniscientDebugger#1]
When running test code that runs fine when compiled with java 1.6. When compiled with 1.8 the following exception is thrown:

Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 54
Exception Details:
  Location:
    com/lambda/tests/TestMyArrayList.<init>()V @16: ifnonnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b201 ca03 6013 01cb 1301 b204 b801 0659
    0x0000010: c700 2657 b201 ca03 60b2 01cf 59c7 000e
    0x0000020: 5713 01ba b801 c059 b301 cf00 1301 cb13
    0x0000030: 01b2 04b8 010a 4c2a b700 08b2 01ca 0360
    0x0000040: 2bb8 00ea b1                           

```
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.getDeclaredMethod(Class.java:2128)
at com.lambda.Debugger.Debugger.runTarget(Debugger.java:1131)
at com.lambda.Debugger.Debugger.runMain(Debugger.java:1036)
at com.lambda.Debugger.Debugger.main2(Debugger.java:1028)
at com.lambda.Debugger.Debugger.main(Debugger.java:967)
```

https://github.com/OmniscientDebugger/LewisOmniscientDebugger/blob/master/src/main/java/com/lambda/Debugger/Debugger.java#L1131

**Comment by madhephaestus** [comment]
From Bill via email:
"Kevin,

Oh, my! But it's been a while.

I finally started to take an actual look at the ODB & JVM changes.

It seems that the Java 8 verifier has a few limitations (aka bugs) that the old one didn't. I understand they are planning on fixing this "feature."

In the meantime, it is sufficient to simply not use the verifier:

# alias debug java -noverify -Xms400100100 -Xmx400100100 -DMEMORY=400100100 -cp $HOME/Debugger:. com.lambda.Debugger.Debugger

"
