### ISSUE TITLE
Java 1.6 runtime issues

### ISSUE THREAD

**Issue by madhephaestus** [OmniscientDebugger/LewisOmniscientDebugger#2]
When using javax/xml/parsers/DocumentBuilderFactory the following java.lang.VerifyError occurs:

This was an attempt to debug an application compiled for Java 1.6. 

class junit.test.neuronrobotics.utilities.ParallelArmTest.main threw java.lang.VerifyError: Expecting a stackmap frame at branch target 38
Exception Details:
  Location:
    javax/xml/parsers/DocumentBuilderFactory.setValidating(Z)V @17: ifnonnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b202 0f10 0c60 1302 3c13 023b 05b8 014d
    0x0000010: 59c7 0015 57b2 020f 100c 602a 1302 3c13
    0x0000020: 023b 05b8 0151 4d2a 1b36 0459 1504 b202
    0x0000030: 0f10 0c60 1302 152c b801 d1b5 0002 b202
    0x0000040: 0f10 0d60 2cb8 0131 b1                 

java.lang.VerifyError: Expecting a stackmap frame at branch target 38
Exception Details:
  Location:
    javax/xml/parsers/DocumentBuilderFactory.setValidating(Z)V @17: ifnonnull
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b202 0f10 0c60 1302 3c13 023b 05b8 014d
    0x0000010: 59c7 0015 57b2 020f 100c 602a 1302 3c13
    0x0000020: 023b 05b8 0151 4d2a 1b36 0459 1504 b202
    0x0000030: 0f10 0c60 1302 152c b801 d1b5 0002 b202
    0x0000040: 0f10 0d60 2cb8 0131 b1  
ODB: 28.Mar.07 run complete.

```
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:264)
at com.neuronrobotics.sdk.addons.kinematics.xml.XmlFactory.getAllNodesDocument(XmlFactory.java:39)
at com.neuronrobotics.sdk.addons.kinematics.MobileBase.<init>(MobileBase.java:67)
at junit.test.neuronrobotics.utilities.ParallelArmTest.main(ParallelArmTest.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.lambda.Debugger.Debugger.runTarget(Debugger.java:1141)
at com.lambda.Debugger.Debugger.runMain(Debugger.java:1036)
at com.lambda.Debugger.Debugger.main2(Debugger.java:1028)
at com.lambda.Debugger.Debugger.main(Debugger.java:967)
```

**Comment by madhephaestus** [comment]
[odb-test.zip](https://github.com/OmniscientDebugger/LewisOmniscientDebugger/files/320798/odb-test.zip)

Here is executable code with the error

**Comment by madhephaestus** [comment]
From Bill via email:
"Kevin,

Oh, my! But it's been a while.

I finally started to take an actual look at the ODB & JVM changes.

It seems that the Java 8 verifier has a few limitations (aka bugs) that the old one didn't. I understand they are planning on fixing this "feature."

In the meantime, it is sufficient to simply not use the verifier:

# alias debug java -noverify -Xms400100100 -Xmx400100100 -DMEMORY=400100100 -cp $HOME/Debugger:. com.lambda.Debugger.Debugger

"
